spring.application.name=crm
spring.datasource.url=jdbc:mysql://localhost:3306/posicionup
spring.datasource.username=root
spring.datasource.password=AgenciaMarketing2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=posicionup.agencia@gmail.com
spring.mail.password=bkjh wrmo bwid idmx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.address=0.0.0.0